# Lab 6 Manual Guide: Comparison of Different Regression Algorithms

## Objective

This lab compares three regression models on the same dataset:
- Linear Regression
- Decision Tree Regression
- Random Forest Regression

The goal is to train each model, evaluate it with mean absolute error (MAE), and compare the results on both the training set and the test set.

## Importing the libraries

In [19]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn import tree
from sklearn.ensemble import RandomForestRegressor

### importing the libraries

`pandas` is used for loading the dataset, `numpy` supports numerical operations, and scikit-learn provides the regression models and the MAE metric used for evaluation.

## Importing the dataset

In [20]:
df = pd.read_csv('50_Startups.csv')
df.head()

,R&D Spend,Administration,Marketing Spend,Profit
0,165349.20,136897.80,471784.10,192261.83
1,162597.70,151377.59,443898.53,191792.06
2,153441.51,101145.55,407934.54,191050.39
3,144372.41,118671.85,383199.62,182901.99
4,142107.34,91391.77,366168.42,166187.94


### loading the dataset

The `50_Startups.csv` file contains startup data used to predict profit. The notebook first loads the CSV file and previews the first few rows so the structure of the dataset can be inspected before modeling.

# Splitting the data set into features(Independent Variables) and Outcome(dependent variable)

In [ ]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

[[165349.2  136897.8  471784.1 ]
 [162597.7  151377.59 443898.53]
 [153441.51 101145.55 407934.54]
 [144372.41 118671.85 383199.62]
 [142107.34  91391.77 366168.42]
 [131876.9   99814.71 362861.36]
 [134615.46 147198.87 127716.82]
 [130298.13 145530.06 323876.68]
 [120542.52 148718.95 311613.29]
 [123334.88 108679.17 304981.62]
 [101913.08 110594.11 229160.95]
 [100671.96  91790.61 249744.55]
 [ 93863.75 127320.38 249839.44]
 [ 91992.39 135495.07 252664.93]
 [119943.24 156547.42 256512.92]
 [114523.61 122616.84 261776.23]
 [ 78013.11 121597.55 264346.06]
 [ 94657.16 145077.58 282574.31]
 [ 91749.16 114175.79 294919.57]
 [ 86419.7  153514.11      0.  ]
 [ 76253.86 113867.3  298664.47]
 [ 78389.47 153773.43 299737.29]
 [ 73994.56 122782.75 303319.26]
 [ 67532.53 105751.03 304768.73]
 [ 77044.01  99281.34 140574.81]
 [ 64664.71 139553.16 137962.62]
 [ 75328.87 144135.98 134050.07]
 [ 72107.6  127864.55 353183.81]
 [ 66051.52 182645.56 118148.2 ]
 [ 65605.48 153032.06 107138.38]
 [ 61994.4

In [23]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train ,y_test = train_test_split (df[['R&D Spend', 'Administration', 'Marketing Spend']],df['Profit'],test_size=0.33,random_state=3)

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 3)

### splitting the data set into features and target

`X` stores the independent variables and `y` stores the dependent variable. The dataset is then split into training and test sets so each model can be trained on one part of the data and checked on unseen data for fair comparison.

# **Linear Regression**

### linear regression

This section fits a linear regression model on the training data and prints the MAE for both the training and test sets. The lower the MAE, the better the model fits the data.

In [ ]:
model1 = LinearRegression()
model1.fit(X_train, y_train)

# Print coefficients
print(f"Intercept (b0) = {model1.intercept_:.2f}")
print(f"Slope (b1) = {model1.coef_[0]:.2f}")
print(f"Equation: y = {model1.intercept_:.2f} + {model1.coef_[0]:.2f}x")
print()

print("Linear Regression")
print("====================")
y_pred_train1 = model1.predict(X_train)
MAE_train = mean_absolute_error(y_train, y_pred_train1)
print("Linear Regression Train set: MAE ${:.2f}".format(MAE_train))

y_pred_test1 = model1.predict(X_test)
MAE_test = mean_absolute_error(y_test, y_pred_test1)
print("Linear Regression Test set: MAE ${:.2f}".format(MAE_test))
print("====================\n")




Linear Regression
Linear Regression Train set: MAE $6426.90
Linear Regression Test set: MAE $7688.71



# **Decision Tree Regression**

### decision tree regression

The decision tree model learns a set of split rules from the training data. Here, `max_depth=2` keeps the tree small and easier to compare with the other regression models.

In [ ]:

model2 = tree.DecisionTreeRegressor(max_depth=2, random_state = 3)
model2.fit(X_train, y_train)

print("Decision Tree")
print("==============================")
y_pred_train2 = model2.predict(X_train)
MAE_train2 = mean_absolute_error(y_train, y_pred_train2)
print("Decision Tree Train set: MAE ${:.2f}".format(MAE_train2))

y_pred_test2 = model2.predict(X_test)
MAE_test2 = mean_absolute_error(y_test, y_pred_test2)
print("Decision Tree Test set: MAE ${:.2f}".format(MAE_test2))
print("==============================\n")

Decision Tree
Decision Tree Train set: MAE $10005.74
Decision Tree Test set: MAE $16843.54



# **Random forest Regression**

### random forest regression

Random forest combines many decision trees to reduce overfitting and usually gives a stronger baseline than a single tree. This section trains the model and reports MAE on the training and test sets.

In [ ]:

model3 = RandomForestRegressor(random_state=3)
model3.fit(X_train, y_train)

print("Random Forest Regressor")
print("==================================================")
y_pred_train3 = model3.predict(X_train)
MAE_train3 = mean_absolute_error(y_train, y_pred_train3)
print("Random Forest Regressor TrainSet: MAE ${:.2f}".format(MAE_train3))

y_pred_test3 = model3.predict(X_test)
MAE_test3 = mean_absolute_error(y_test, y_pred_test3)
print("Random Forest Regressor TestSet: MAE ${:.2f}".format(MAE_test3))
print("==================================================\n")


Random Forest Regressor
Random Forest Regressor TrainSet: MAE $2940.06
Random Forest Regressor TestSet: MAE $7593.87



## Conclusion

After running the notebook, compare the train and test MAE values for all three models. The preferred model is the one with the lowest test MAE, because it generalizes better to unseen data.